
apiVersion: v1
kind: Service
metadata:
  name: customerorderservicesapp
  labels:
    app: customerorderservicesapp
spec:
  ports:
    - port: 9080
  selector:
    app: customerorderservicesapp
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: customerorderservicesapp
  name: customerorderservicesapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customerorderservicesapp
    spec:
      containers:
      - image: mycluster.icp:8500/default/customerorderservicesapp:latest
        name: customerorderservicesapp
        ports:
        - containerPort: 9080
          protocol: TCP
